language: python
sudo: false
python:
    - "2.7"
env:
  global:
    - secure: "qhsOZSJH7OBoIbw5naEm1kL0qrVtw/EyEu/R0SXd4lEa8r6uYToDwtfA6HTiGqecF0Xd3OsZD5EhkEpTPtWSlFNsFz1qzJfIFqvAx/cEmKTNDkEHwsI+BIm/CHMzTXiiCBObBcBiKimbzorsShJfKQZ9X+C8nFs32p00P1kvGT31g5jUwAp2dWH/PgDIbYYUkaermokj4BvHUdKhffN10sZl/bDj2gyxwyy9xfJp4pIq1R2oksXQ1FFd5AuV7owSZXZCcrF858OTDEiI8KiyYeUPs1nsBAtXSsI6HzgTjmdmsQsSi51oAKPfpdP73Z/vzvgi+SEUR1H71VJ/3fFeIkCx0HTje3pmebjKeFmtkoIAvW1AY8hfHSmZQ/N0s7nz/+qhoHvzSoCEotm0nbghVthNnLwpNQ7qNAzuDiQKudM13kJ4WMKiRDYLRb4RKM3BIqTal5X3beLPC9M21otVH5it31skJyZJaBrqmWHiNbY/hzuZwHD4k1wqiZn4mjeGmlTDDS3uRWLdth9jigwDUBmUzU3qxVcvuvl8Y/4uCSDAsm1U2DhJzd/BA7wO05C0BYsfLIn1VpBrzruEBj/dQwvKzB/f+hK8hlZ4orSFpzMvGpWFsQYqbPOhCmb0I+LghQ+v4FK19a2V3g01WN8FhTaWFpejRWT/KwVXq2O7Gdc=" # FEC_CF_USERNAME
    - secure: "c2yqTMHT0sp/YWlSxUpI+2vYtjU88liYsPb2lt/TzABFVZbZZf/XjunyvQpw969TmD1k5huE/6qBD4SKHMa/VTCiSxpay6HuWOBdx4Hutv7rY/8e0TpkNCc9v+ekKj/6/OgA2IkrlJn1hEAErlTfygqijH7z9X8y4bXgDEslb7j2+aoF1gQx96MjEV2dwourE75rFzyOSMK44IrmcNCa20ZyAi7H9IFYxsX7XC8bb/weUkaZrSe3jXuWWRKh1SeXBFaIJ08oH4MwVvQWaV6Vfuy2fg+/+Q32N3KYvTsstkgsQpiwFWKTK9cGog3LFme/mqG+V0V2E4xWRjmkMduDxIFjUJNMIpRGCUysqV98pUyXg3hTtzH2wbtr45PbNeM7jIeWochoCFa/lcKeayn53NGOl51Dn7SHS2cWZdp3G2jnZb9TR8xKp4QRKLsMuFtAcN+f8Mv8C7QNWzOLewRXfHyQ1OcyRxE0icgoI3ZTcXW/ikg1abH4myOCoSnXwT6Qh1ojGxFm56u6glCayWynx6LOZfF8BumNpKhlJUeJHJgMUDQMWeK10FzNydwEOSl4aml5uo3dO2JUF8yR+yrxAVKuTX3q768KkVzNJ8vTK7P+F8MHAJAjnTLc8lGTpuUy7Ljz7BMGhDLTg7qtwwLO27tXZWLpPRIufhPlRQrxJuI=" # FEC_CF_PASSWORD

before_install:
  - gem install sass

install:
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
    - pip install -r requirements_dev.txt
    - npm install -g grunt-cli bower
    - npm install
script:
    - npm run build
    - python manage.py migrate --fake-initial
    - python manage.py compile_frontend
    - python manage.py test

before_deploy:
  - mkdir $HOME/bin
  - export PATH=$HOME/bin:$PATH
  - travis_retry curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.15.0" | tar xzv -C $HOME/bin
  - travis_retry cf install-plugin autopilot -f -r CF-Community

# Simple smoke tests
after_deploy:
  - curl --silent --fail --head https://fec-dev-eregs.18f.gov/regulations || travis_terminate $?
  - curl --silent --fail --get https://fec-dev-eregs.18f.gov/regulations/api/regulation/2 > /dev/null || travis_terminate $?

deploy:
  - provider: script
    skip_cleanup: true
    script: ./bin/cf_deploy.sh eregs fec dev manifest.dev.yml
    on:
      branch: feature/migrate-to-govcloud

  - provider: script
    skip_cleanup: true
    script: ./bin/cf_deploy.sh eregs fec stage manifest.stage.yml
    on:
      branch: release/*

  - provider: script
    skip_cleanup: true
    script: ./bin/cf_deploy.sh eregs fec prod manifest.prod.yml
    on:
      tags: true
