language: python
sudo: false
python:
    - "2.7"
env:
  global:
    - secure: "QGZfUq1EyY2zNPmHcEt0BWpd9CD9RueWos3V4WBW+8n58+jyRfo98gysAgGKm+suXjockpozg6p6ahesxE37OkaV5o7gnCTE6FPSluICikIfn3B+W1YQB1lHmh0S3jASaGLu9wSkCWyyyRQ10TCtH3qb1MTMNOFu3EKNfD/MRuBtwlyOSRXTWQV66yyZGyVClf4NLKYxbcZSwNUvDySu8pt1gXZnSGUl1f5xbgaq0F0nvi/xuI9u+9duz4Qxip01OTh2qFcSdWHV89MT/pOet5aqgkseZcj5hIKZHUrTeMksfAR32pg2k1y6hxankUNdcCiZqDkMCjJQ7B8p0Gl82k6fcWKGesO6MY4bU+zhet2zd74sEVq8LxKw0qTF15byryqOA1k/Qd2qJxy1Yz9nKSycLlTeY+aSbX8GOt/CBtVnIkLWStrkO13v4KWxpwQI2e/DbMC5FHmvhhc6KOM2YMxdDHZ1KmoD/qK62dFcm1ZyZbzy6ld8K0VvMdgcKng5yQkUA4ETNiMteY2WWR/SCXA8v9Tqc2YB3pL802Ab1ZvszZ5dJUoIPR7sjOYUyINjyKUrYdrBeQN9OfCKU5f185vOzR1GvM9XC3jsKznRJmaYRjU7dqCbkjmQubTSLE5Umn5Ktx3EK4u6s2sjoTJ0HhaURqykivQrOn8p0JNUEPQ=" # FEC_CF_USERNAME
    - secure: "qcMGiSFpBwtPFtz8oMWez+AndQzjumyPsUcUn+crRdA3yXNdmcx3am/d1NpyGKRfkr603fVo2vxl1cE1dLi9JoCN/ASM0KG1cgeMse/GyDXX+SnT+55ALUki2J3vrpMUMKgngDJn1fMtaq8EhXqNN9kiXZ+xp1B9e+psHA7Iuuv74YLbM+vCcWsrPe7Euw7tEytCuMk9CVLENfn1MhLiZS33oQ5YWYSJp0fvwOz9zT640SWw0wAKmyBS7yv3H+jdXvhMbsZU/xzatW0rUPAquUrsx/5p0o+Ryov363IbrkNeK+CCaOB/zZhCoEtvGBzCDbWovrpzi8D8EZL17rQiNxys7R5sCGsY/MHFGAVcHbyyqwepcaE0bwnIz97vZiFLVm+VTnNOWM/xmifTDVmamwXgPpr7BJFkPzS7QzxJjt78fz2jn5FSarAEzB+aUCfCJI1ImYsS2f7OxO4rOXzUNI/qIoolAJPk9wk6hn96abmo/4bxU31e84aEQba7VuHR4r6n4twQ5VZmq6hoip8vJhyQIJ3LuQUaPg7S0IvDOTPtfkPeA6j6rGudhqxSV+N3r2TXOwoTMgDlW0cpYqvjANRG/SepiDqXKQQZjUElTcpyI/eHRtYRhpQ7wsDiFK0yNO11F2pxDntkblUynPk80JmuCQCdwMj4v8QW4gdzjeE=" # FEC_CF_PASSWORD

before_install:
  - gem install sass

install:
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
    - pip install -r requirements_dev.txt
    - npm install -g grunt-cli bower
    - npm install
script:
    - npm run build
    - python manage.py migrate --fake-initial
    - python manage.py compile_frontend
    - python manage.py test

before_deploy:
  - mkdir $HOME/bin
  - export PATH=$HOME/bin:$PATH
  - travis_retry curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.15.0" | tar xzv -C $HOME/bin
  - travis_retry cf install-plugin autopilot -f -r CF-Community

# Simple smoke tests
after_deploy:
  - curl --silent --fail --head https://fec-dev-eregs.18f.gov || travis_terminate $?
  - curl --silent --fail --get https://fec-dev-eregs.18f.gov/api/regulation/2 > /dev/null || travis_terminate $?

deploy:
  - provider: script
    skip_cleanup: true
    script: ./bin/cf_deploy.sh eregs fec dev manifest.dev.yml
    on:
      branch: develop

  - provider: script
    skip_cleanup: true
    script: ./bin/cf_deploy.sh eregs fec stage manifest.stage.yml
    on:
      branch: release/*

  - provider: script
    skip_cleanup: true
    script: ./bin/cf_deploy.sh eregs fec prod manifest.prod.yml
    on:
      tags: true
