language: python
sudo: false
python:
    - "2.7"
env:
  global:
    - secure: "bWqvrpIh4IBlVvckjX+7Cwg/Fh7C0NU02MgsFsgZ8Ur6kt8oHKNv0ax2rRVGopFTVZVUXlFbo+mFm5ha5x9K4uVHo4awq9pWuVR9X7TySsLiBKVDPEP0ziZ54hs0Wb/t7MdLBFaowLun63gheLtmSZZmHHHSHIRTnauEDcKBxaI=" # FEC_CF_USERNAME
    - secure: "UQnMw00cgmpZcO1ky3YG8uZ4vweaXr+iVyzXaRceZDz1n5SegTy9bQHermrsLUlac/bAKmyHBsWgpt/Nym7JIw35E3OVEl6ttdeqAsAtyZKE+thNQsAXn81+sD31dOPdoLZbQT8MjixsxQyjGdlPJdfqFz1hd1RaOyQ2dnXTR/c=" # FEC_CF_PASSWORD

before_install:
  - gem install sass

install:
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
    - pip install -r requirements_dev.txt
    - npm install -g grunt-cli bower
    - npm install
script:
    - npm run build
    - python manage.py migrate --fake-initial
    - python manage.py compile_frontend
    - python manage.py test

before_deploy:
  - mkdir $HOME/bin
  - export PATH=$HOME/bin:$PATH
  - travis_retry curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.15.0" | tar xzv -C $HOME/bin
  - travis_retry cf install-plugin autopilot -f -r CF-Community

# Simple smoke tests
after_deploy:
  - curl --silent --fail --head https://fec-dev-eregs.18f.gov/regulations || travis_terminate $?
  - curl --silent --fail --get https://fec-dev-eregs.18f.gov/regulations/api/regulation/2 > /dev/null || travis_terminate $?

deploy:
  - provider: script
    skip_cleanup: true
    script: ./bin/cf_deploy.sh eregs fec dev manifest.dev.yml
    on:
      branch: feature/migrate-to-govcloud

  - provider: script
    skip_cleanup: true
    script: ./bin/cf_deploy.sh eregs fec stage manifest.stage.yml
    on:
      branch: release/*

  - provider: script
    skip_cleanup: true
    script: ./bin/cf_deploy.sh eregs fec prod manifest.prod.yml
    on:
      tags: true
