language: python
sudo: false
python:
    - "2.7"
env:
  global:
    - CF_DEPLOY_USER=fec_deployer
    - secure: "VnsiuyLMCUJbPCZsOKLMzFDj5T4KIokimyZ0ckhRaI4xgzP4nM/oeuy0zRbhx4mn6tRvJCAkUC8VIJJLO5adKTHSU2lK2iuTw1FmCWb9NsoIXt/8dksKFJdjJWoaIJeZGcpTo/JpPbG+LdV02/sndh6AJEQ2RAyZNIVOwFI5u5VhBZpIKURaliPrY1+LV4a0ooNIC1DLGHx1bpy8OXwz/584q0z8dkAAckNStEOgl7DIaWbpODYUnvSFlLTOqtdalf2Nfmi/Oxuk+/wyL8Xd9b5PT9zMCsDUnSIMZvZhosWlsGGIqtmhEtrwz/F2EXAEFQg1uf8oMpwhU8zViQxBxwdzWsQOlczLo7J88edUwOY2fCf5hD6JKsPtjnsOF6HH8FL63xO9b9dbfRuGOMVZ4nOvdHwAbWfBTqBDljBtifZw//Cy8x4SCHLgAl1QMC3d4bY9/UDUu3Y86l4mQ8xceRb/gf67qiHewyRpfQB7zOGx2OxmXsLKkeFgj0hMzfa8+YksF1j8BFZcukDT7g3qOQg4iOkyZ0L6BUxdBlulLbzPszsOQ0wo0qxOFaw4UfRC2FOxIEV+c5f2L7vGTK4R8ovK9TmWant1aE5ThKaJ6l8+Pv7Aa2SGlnfa55RsB4R8FddlG9O3OYQqxBWl31sRPsesQjWR/c3c/533VWBcmVA=" # CF_DEPLOY_PASSWORD
install:
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
    - pip install -r requirements_dev.txt
    - npm install -g grunt-cli bower
    - npm install
script:
    - npm run build
    - python manage.py migrate --fake-initial
    - python manage.py compile_frontend
    - python manage.py test

before_deploy:
  - mkdir $HOME/bin
  - export PATH=$HOME/bin:$PATH
  - travis_retry curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.15.0" | tar xzv -C $HOME/bin
  - travis_retry cf install-plugin autopilot -f -r CF-Community

# Simple smoke tests
after_deploy:
  - curl --silent --fail --head https://fec-dev-eregs.18f.gov || travis_terminate $?
  - curl --silent --fail --get https://fec-dev-eregs.18f.gov/api/regulation/2 > /dev/null || travis_terminate $?

deploy:
  - provider: script
    skip_cleanup: true
    script: ./bin/cf_deploy.sh eregs fec dev manifest.dev.yml
    on:
      branch: develop

  - provider: script
    skip_cleanup: true
    script: ./bin/cf_deploy.sh eregs fec stage manifest.stage.yml
    on:
      branch: release/*

  - provider: script
    skip_cleanup: true
    script: ./bin/cf_deploy.sh eregs fec prod manifest.prod.yml
    on:
      tags: true
